version: 2

jobs:

  "r-test": &test-template
    working_directory: ~/dash
    docker:
      - image: byronz/dashr:ci
        environment:
          PERCY_ENABLE: 0

    steps:
      - checkout

      - run:
          name: ℹ️ CI Context
          command: |
            echo "TRIGGERER: ${CIRCLE_USERNAME}"
            echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
            echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
            echo "BRANCH: ${CIRCLE_BRANCH}"
            echo "RUNNING JOB: ${CIRCLE_JOB}"
            echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
            echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
            echo $CIRCLE_JOB > circlejob.txt

      - run:
          name: 🚧 install R dependencies
          command: |
              git clone --depth 1 https://github.com/plotly/dash-core-components.git
              git clone --depth 1 https://github.com/plotly/dash-html-components.git
              git clone --depth 1 https://github.com/plotly/dash-table.git
              sudo Rscript -e 'install.packages("remotes")'
              sudo R CMD INSTALL dash-core-components
              sudo R CMD INSTALL dash-html-components
              sudo R CMD INSTALL dash-table
              sudo R CMD INSTALL .

      - run:
          name: ⚙️ run integration test
          command: |
            python -m venv venv
            . venv/bin/activate
            git clone -b dashr-test-support --depth 1 https://github.com/plotly/dash.git
            cd dash && pip install -e .[testing] && cd ..
            export PATH=$PATH:/home/circleci/.local/bin/
            echo "running integration"
            pytest tests/integration/

workflows:
  version: 2
  build:
    jobs:
      - "r-test"
